name: On Push

on:
  push:
    branches:
      - main
      - QA
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.REPOSITORY }}

jobs:

  build:  
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GH_ACTOR }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Create production.env file
        run: |
          mkdir -p app/env
          echo "APP_ENV=production" > app/env/production.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> app/env/production.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> app/env/production.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> app/env/production.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> app/env/production.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> app/env/production.env
          
        shell: bash

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
